[I] DCASE 2017::Acoustic Scene Classification / Baseline System
[I] 
[I] Initialize [Development setup][folds]
[I] ==================================================
[I] 
[I]   System              
[I]     Name                 : DCASE 2017::Acoustic Scene Classification / Baseline System
[I]     Parameter set        : SET1
[I]     Setup                : Python[3.6.2], Numpy[1.13.3], sklearn[0.19.1], Keras[2.1.1], Theano[0.9.0], Librosa[0.5.1]
[I]   Dataset             
[I]     Name                 : TUT-acoustic-scenes-2017-development
[I]     Active folds         : [1, 2, 3, 4]
[I]   Evaluator           
[I]     Save path            : applications/system/task1/evaluator
[I]   DONE     [0:00:00.458578 ] 
[I] 
[I] Feature extractor
[I] ==================================================
[I] 
[I]   DONE     [0:00:03.387474 ] [4680 items] 
[I] 
[I] Feature normalizer
[I] ==================================================
[I] 
[I]   DONE     [0:00:00.004199 ] 
[I] 
[I] System training
[I] ==================================================
[I] 
[D]   Validation set statistics
[D]   Scene label          | Validation amount (%) 
[D]   -------------------- + -------------------- 
[D]   beach                | 12.82 
[D]   bus                  | 10.26 
[D]   cafe/restaurant      | 12.82 
[D]   car                  | 12.82 
[D]   city_center          | 12.82 
[D]   forest_path          | 11.54 
[D]   grocery_store        | 12.82 
[D]   home                 | 15.38 
[D]   library              | 14.10 
[D]   metro_station        | 10.26 
[D]   office               | 10.26 
[D]   park                 | 14.10 
[D]   residential_area     | 12.82 
[D]   train                | 10.26 
[D]   tram                 | 12.82 
[D]   
[D]   Training items 	[1540575]
[D]   Validation items 	[217935]
[D]   Keras
[D]     Backend 	[tensorflow]
[D]     BLAS library	[MKL]		(Threads[1], MKL_CBWR[COMPATIBLE])
[D]   Tensorflow
[D]     Device 		[cpu]
[D]   
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "applications/task1.py", line 290, in <module>
    sys.exit(main(sys.argv))
  File "applications/task1.py", line 224, in main
    app.system_training()
  File "/home/student030/vcwu/rbe595/proj/DCASE2017-baseline-system/dcase_framework/decorators.py", line 38, in function_wrapper
    to_return = func(*args, **kwargs)
  File "/home/student030/vcwu/rbe595/proj/DCASE2017-baseline-system/dcase_framework/application_core.py", line 1358, in system_training
    validation_files=validation_files
  File "/home/student030/vcwu/rbe595/proj/DCASE2017-baseline-system/dcase_framework/learners.py", line 1133, in learn
    import keras
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 3, in <module>
    from .. import backend as K
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/site-packages/keras/backend/__init__.py", line 83, in <module>
    from .tensorflow_backend import *
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/student030/anaconda3_redux/envs/dlnn_gpu/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
